---
#########################################################
## Cockpit configure action                            ##
#########################################################

#########################################################
## Branding                                            ##
#########################################################

- name: Add custom logo to Cockpit login page...
  become: true
  when: cockpit_branding_logo is defined
  block:
    # Copy branding from template to folder
    - name: Configure Cockpit branding...
      ansible.builtin.template:
        src: branding.css.j2
        dest: /usr/share/cockpit/branding/rhel/branding.css
        mode: "0644"

    # Copy custom logo to Cockpit branding folder
    - name: Copy custom logo to Cockpit branding folder...
      ansible.builtin.copy:
        src: "{{ cockpit_branding_logo }}"
        dest: /usr/share/cockpit/branding/rhel/logo.png
        mode: "0644"

- name: Add custom banner to Cockpit login page...
  when: cockpit_branding_banner is defined
  become: true
  block:
    # Copy banner to Cockpit configuration folder
    - name: Copy banner to Cockpit configuration folder...
      ansible.builtin.copy:
        src: "{{ cockpit_branding_banner }}"
        dest: /etc/issue.cockpit
        mode: "0644"

    # Ensure the cockpit.conf file exists
    - name: Ensure Cockpit config directory exists...
      ansible.builtin.file:
        path: /etc/cockpit
        state: directory
        mode: "0755"

    # Ensure banner= directive is present in Cockpit configuration file
    - name: Ensure banner= directive is present in Cockpit configuration file...
      ansible.builtin.blockinfile:
        path: /etc/cockpit/cockpit.conf
        block: |
          [Session]
          Banner=/etc/issue.cockpit

# Configure dnf automatic updates
- name: Configure dnf automatic updates...
  ansible.builtin.copy:
    content: |
      [commands]
      apply_updates = yes
      upgrade_type = security
      [emitters]
      emit_via = motd
    dest: /etc/dnf/automatic.conf
    mode: "0644"

# Enable timer
- name: Enable dnf-automatic timer...
  become: true
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: started
    enabled: true

# Enable kpatch service
- name: Enable kpatch service...
  become: true
  ansible.builtin.service:
    name: kpatch.service
    state: started
    enabled: true

#########################################################
## Post-configuration                                  ##
#########################################################

# Restart via handler only when changes occurred

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    cockpit_branding_logo:
    cockpit_branding_banner:
