---

#########################################################
## Gather information                                  ##
#########################################################

# Set `action_parameters` variable to parameter list in actions where key is equal to `action`
- name: "Gather action parameters for action ({{ action }})..."
  set_fact:
    action_parameters: "{{ (actions | map('dict2items') | map('first') | selectattr('key', 'equalto', action) | map(attribute='value') | first).parameters }}"

#########################################################
## Branding                                            ##
#########################################################

- name: Add custom logo to Cockpit login page...
  when: cockpit_branding_logo is defined
  block: 

    # Copy branding from template to folder
    - name: Configure Cockpit branding...
      ansible.builtin.template:
        src: branding.css.j2
        dest: "/usr/share/cockpit/branding/rhel/branding.css"
        mode: '0644'
      when: ansible_os_family == 'RedHat'

    # Copy custom logo to Cockpit branding folder
    - name: Copy custom logo to Cockpit branding folder...
      ansible.builtin.copy:
        src: "{{ cockpit_branding_logo }}"
        dest: "/usr/share/cockpit/branding/rhel/logo.png"
        mode: '0644'
      when: ansible_os_family == 'RedHat'

- name: Add custom banner to Cockpit login page...
  when: cockpit_branding_banner is defined
  block:

    # Copy banner to Cockpit configuration folder
    - name: Copy banner to Cockpit configuration folder...
      ansible.builtin.copy:
        src: "{{ cockpit_branding_banner }}"
        dest: "/etc/issue.cockpit"
        mode: '0644'

    # Ensure the cockpit.conf file exists
    - name: Ensure the cockpit.conf file exists...
      ansible.builtin.file:
        path: "/etc/cockpit/cockpit.conf"
        state: touch
        mode: '0644'

    # Ensure banner= directive is present in Cockpit configuration file
    - name: Ensure banner= directive is present in Cockpit configuration file...
      ansible.builtin.blockinfile:
        path: /etc/cockpit/cockpit.conf
        block: |
          [Session]
          Banner=/etc/issue.cockpit

#########################################################
## Post-configuration                                  ##
#########################################################

# Restart Cockpit service
- name: Restart Cockpit service...
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    action_parameters: null
    cockpit_branding_logo: null
    cockpit_branding_banner: null
