---

#########################################################
## Gather information                                  ##
#########################################################

# Gather installed packages
- name: Gather installed packages...
  ansible.builtin.package_facts:
    manager: auto

# Set action_parameters variable to pameter list in actions where key is equal to action
- name: "Gather variables for action ({{ action }})..."
  set_fact:
    action_parameters: "{{ (actions | map('dict2items') | map('first') | selectattr('key', 'equalto', action) | map(attribute='value') | first).parameters }}"

# Check if cockpit service is running
- name: Register Cockpit service...
  ansible.builtin.systemd:
    name: cockpit.socket
  register: cockpit_service_status
  changed_when: false
  failed_when: false
  ignore_errors: true

#########################################################
## Uninstall                                           ##
#########################################################

# Run uninstall if service is running
- name: Run uninstall task if Cockpit service is running...
  ansible.builtin.include_tasks: uninstall.yml
  when: 
    - '"cockpit" in ansible_facts.packages'
    - uninstall is defined
    - uninstall == true

#########################################################
## Pre-installation                                    ##
#########################################################

#########################################################
## Installation                                        ##
#########################################################

# Install cockpit packages
- name: Install Cockpit packages...
  ansible.builtin.package:
    name:
      - cockpit
    state: present

# Check if Podman is installed
- name: Check if Podman is installed...
  ansible.builtin.command: podman --version
  register: podman_version_output
  ignore_errors: true

# Install Cockpit Podman packages
- name: Install Cockpit Podman packages...
  ansible.builtin.package:
    name:
      - cockpit-podman
    state: present
  when: podman_version_output

# Install Cockpit KVM packages
- name: Install Cockpit KVM packages...
  ansible.builtin.package:
    name:
      - cockpit-machines
    state: present
  when: ansible_virtualization_role != 'guest'

# Enable Cockpit service
- name: Enable Cockpit service...
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true

# Enable Cockpit firewall
- name: Allow Cockpit through firewall..
  ansible.posix.firewalld:
    service: cockpit
    permanent: true
    state: enabled
    immediate: true

#########################################################
## Configuration                                       ##
#########################################################

# Configure Cockpit
- name: Start configure task...
  ansible.builtin.include_tasks: configure.yml
  vars:
    action: "configure"

#########################################################
## Post-install                                        ##
#########################################################

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    cockpit_service_status: null
    podman_version_output: null
