---

#########################################################
## Set action                                          ##
#########################################################
# If action variable is not defined, gather status of the service
# If service not installed, set action to install.
# If the service is not started, set action to start.

# Gather installed packages
- name: Gather installed packages...
  ansible.builtin.package_facts:
    manager: auto

# Check if cockpit service is running
- name: Check status of Cockpit service...
  ansible.builtin.systemd:
    name: cockpit.socket
  register: cockpit_service_status
  changed_when: false
  failed_when: false
  ignore_errors: true

# Set action variable when service is not running
- name: Set action (start)...
  ansible.builtin.set_fact:
    action: "start"
  when: cockpit_service_status is defined and cockpit_service_status.status is defined and cockpit_service_status.status.ActiveState is defined and cockpit_service_status.status.ActiveState != 'active'

# Set action to install if cockpit is not installed
- name: Set action (install)...
  ansible.builtin.set_fact:
    action: "install"
  when: "'cockpit' not in ansible_facts.packages"
