---
#########################################################
## Cockpit stop action                                ##
#########################################################

# Stop Cockpit service
- name: Ensure Cockpit service is stopped and disabled...
  become: true
  ansible.builtin.systemd:
    name: cockpit.socket
    state: stopped
    enabled: false
