---

- name: Converge
  hosts: all
  gather_facts: true

  roles:
    - role: cockpit

  tasks:
    - name: Ensure Cockpit is installed
      ansible.builtin.package:
        name: cockpit
        state: present

    - name: Ensure Cockpit service is enabled and started
      ansible.builtin.systemd:
        name: cockpit
        enabled: true
        state: started
